backend:
  name: git-gateway
  repo: gatsby-gitbook-starter # Path to your Github repository
  branch: master # Branch to update (master by default)
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"  

publish_mode: editorial_workflow
show_preview_links: true
local_backend: true
media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  - name: "codeblock" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Codeblock" # Used in the UI, e.g., "New Post"
    folder: "content/codeblock" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Foo", name: "foo", widget: "foo" }
      - { label: "Publish Date", name: "date", widget: "datetime" }  
  - name: "pages" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "New Page" # Used in the UI, e.g., "New Post"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Foo", name: "foo", widget: "foo" }
      - { label: "Publish Date", name: "date", widget: "datetime" }      
